import Head from "next/head";

import ChatBody from "@/Components/ChatBody";
import ChatInput from "@/Components/ChatInput";
import { useState } from "react";

export default function Home() {
  const [data, setData] = useState<{ sender: "ai" | "user"; message: any }[]>(
    []
  );
  const [loading, setLoading] = useState(false);
  return (
    <>
      <Head>
        <title>CHAT GPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://stijndv.com" />
        <link
          rel="stylesheet"
          href="https://stijndv.com/fonts/Eudoxus-Sans.css"
        />
      </Head>
      <div className="bg-[#1A232E] h-screen py-6 relative sm:px-16 px-12 text-white overflow-hidden flex flex-col justify-between  align-middle">
        {/* gradients */}
        <div className="gradient-01 z-0 absolute"></div>
        <div className="gradient-02 z-0 absolute"></div>

        {/* header */}
        <div className="uppercase font-bold  text-2xl text-center mb-3">
          Hãy CHAT VỚI THỊNH THÔNG THÁI
        </div>

        {/* body */}
        <div
          className="h-[90%] overflow-auto w-full max-w-4xl min-w-[20rem] py-8 px-4 self-center
      scrollbar-thumb-slate-400 scrollbar-thin scrollbar-track-gray-tranparent scrollbar-thumb-rounded-md
      "
        >
          <ChatBody data={data} loading={loading} />
        </div>

        {/* input */}
        <div className="w-full max-w-4xl min-w-[20rem] self-center">
          <ChatInput sendMessage={setData} setLoading={setLoading} />
        </div>
      </div>
    </>
  );
}
type PropsChat = {
  message: string;
  sender: "ai" | "user";
};
